services:
  image-analyzer:
    build: .
    image: akramkhan18/image-analyzer:v1.4
    container_name: image-analyzer-container

    volumes:
      - image_input:/app/input_images
      - image_output:/app/output_images
      - image_reports:/app/reports
      - image_logs:/app/logs

    restart: "no"

volumes:
  image_input:
  image_output:
  image_reports:
  image_logs: